[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"

[workspace]
members = ["day_01", "day_02", "day_03", "day_04", "day_05", "day_06", "day_07", "day_08", "day_09", "day_10", "day_11", "day_12", "day_14"]